# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: castep-outputs
author: Jacob Wilkins

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: castep_outputs_manual.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/oerc0122/castep_outputs/  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.doctest'
  - 'sphinxarg.ext'
  config:
    add_module_names: True
    html_theme: "sphinx_book_theme"
    napoleon_include_special_with_doc: True
    napoleon_use_param: True
    autosummary_generate: True
    autoclass_content: 'both'
    autodoc_default_options:
      members: True
      inherited-members: False
      private-members: True
      show-inheritance: True
    autodoc_type_aliases:
      AtomIndex: castep_outputs.utilities.datatypes.AtomIndex
      ThreeVector: castep_outputs.utilities.datatypes.ThreeVector
      SixVector: castep_outputs.utilities.datatypes.SixVector
      ThreeByThreeMatrix: castep_outputs.utilities.datatypes.ThreeByThreeMatrix
      AtomPropBlock: castep_outputs.utilities.datatypes.AtomPropBlock
    intersphinx_mapping:
      python:
        - 'https://docs.python.org/3/'
        - ""
